### ISSUE TITLE
No tie detection in connect four

### ISSUE THREAD

**Issue by olus2000** [lychanl/two-player-games#1]
Method `ConnectFourState.is_finished` returns `False` even if the board is full if there is no winner.

### How to reproduce
1. Prepare a `ConnectFourState` object that has every field filled and no winners.
2. Call `is_finished` method of that object.

### Expected behaviour
Method call returns `True`, because the game is finished.

### Actual behaviour
Method call returns `False`.

### Workaround
In addition to checking the `is_finished` method to see if the game is finished the `get_moves` method should be checked because the tie state has no valid moves.

### Proposed fix
Add an iteration over the top fields of each column to the `is_finished` method that will detect a full board.

**Comment by lychanl** [comment]
Thank you bringing up this issue, it is now resolved.
